# Generated by Django 4.1.2 on 2022-10-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bflowers', '0002_category_alter_product_options_product_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
