# Generated by Django 4.1.2 on 2022-10-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCost',
        ),
    ]
