# Generated by Django 4.1.2 on 2022-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bflowers', '0003_alter_category_options_alter_product_options'),
        ('cart', '0007_rename_item_cartproducts_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_products', to='bflowers.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CartProducts',
        ),
    ]
