# Generated by Django 4.1.2 on 2022-10-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bflowers', '0003_alter_category_options_alter_product_options'),
        ('cart', '0008_cart_products_cart_quantity_delete_cartproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='bflowers.product'),
        ),
    ]
